version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: e-shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/e-shop
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
